### ISSUE TITLE
Error for dynamic permalink in JS

### ISSUE THREAD

**Issue by solution-loisir** [11ty/eleventy-plugin-webc#49] opened 2023-02-04 14:27 UTC
You could also use a JS function for this as well (with JS front matter) and bypass the webc parsing altogether:

```yaml
---js
{
  permalink: function(data) {
    return "`/${this.slugify(data.item.title)}/`";
  }
}
---
```

https://www.11ty.dev/docs/data-frontmatter/#javascript-front-matter

_Originally posted by @zachleat in https://github.com/11ty/eleventy-plugin-webc/issues/42#issuecomment-1374153546_

**Comment by solution-loisir** [comment] 2023-02-04 14:49
I'm getting a syntax error when defining dynamic permalink in JS frontmatter like above or in JS data file (see also the comments in #32). 

For this frontmatter:
```js
---js
{
  title: "About",
  description: "This page explains what WebC is all about!",
  lang: "en",
  permalink: function(data) {
    return "`/${this.slugify(data.title)}/`";
  }
}
---
```
I get this error:
<details>
<summary><code>Function statements require a function name (via SyntaxError)</code></summary>

```bash
[11ty] Original error stack trace: evalmachine.<anonymous>:1
[11ty] function(data) {
[11ty] ^^^^^^^^
[11ty] 
[11ty] SyntaxError: Function statements require a function name
[11ty]     at new Script (node:vm:100:7)
[11ty]     at createScript (node:vm:257:10)
[11ty]     at Object.runInNewContext (node:vm:298:10)
[11ty]     at Function.evaluateScript (/home/mathieu/webc-starter-kit/node_modules/@11ty/webc/src/moduleScript.cjs:62:25)
[11ty]     at Object.<anonymous> (/home/mathieu/webc-starter-kit/node_modules/@11ty/eleventy-plugin-webc/src/eleventyWebcTemplate.js:70:26)
[11ty]     at Template._renderFunction (/home/mathieu/webc-starter-kit/node_modules/@11ty/eleventy/src/TemplateContent.js:398:27)
[11ty]     at Template.renderPermalink (/home/mathieu/webc-starter-kit/node_modules/@11ty/eleventy/src/TemplateContent.js:447:19)
[11ty]     at async Template._getLink (/home/mathieu/webc-starter-kit/node_modules/@11ty/eleventy/src/Template.js:252:24)
[11ty]     at async Template.getOutputLocations (/home/mathieu/webc-starter-kit/node_modules/@11ty/eleventy/src/Template.js:302:16)
[11ty]     at async Template.addComputedData (/home/mathieu/webc-starter-kit/node_modules/@11ty/eleventy/src/Template.js:614:28)
[11ty] Wrote 0 files in 0.23 seconds (v2.0.0-beta.2)
```
</details>

Maybe I doing something wrong. As stated in #42, using dynamic attribute syntax in YAML frontmatter does work ex. 
```yaml
permalink: "`/${page.fileSlug}/`"
```
It just doesn't seem to work in JS for me.

**Comment by solution-loisir** [comment] 2023-02-10 11:21
Seems to be the same issue as #50, and especially to [this comment](https://github.com/11ty/eleventy-plugin-webc/issues/50#issuecomment-1423299083).

**Comment by zachleat** [comment] 2023-02-22 23:17
Duplicate of #32, please subscribe over there!

Related: #47 #52

**Closed by zachleat** 2023-02-22 23:17 UTC
