### ISSUE TITLE
Disable bundling but process

### ISSUE THREAD

**Issue by cfjedimaster** [11ty/eleventy-plugin-webc#31] opened 2022-11-21 22:15 UTC
So imagine you don't want bundling for a script tag. You can just add `webc:keep` and that works. But, if you have any code in there you expect webc to process, it won't. Should this work?

```html
<script webc:keep>
let msg = `
<p @raw="name"></p>
`;
</script>
```

**Comment by zachleat** [comment] 2022-12-02 23:25
```
<script webc:keep webc:is="template">
`<p @raw="name"></p>`;
</script>
```

is what you’ll want AFTER WebC v0.8.0 ships.

Duplicate of https://github.com/11ty/webc/issues/78 please follow along over there!

**Closed by zachleat** 2022-12-02 23:25 UTC
Labels: bug
